server:
  #端口
  port: 8084
  servlet:
    #前缀路径
    context-path: /dqgac
    session:
      #超时时间格式：P3DT3H3M3S 3天3小时3分3秒
      timeout: PT3H

spring:
  resources:
    static-locations: classpath:/static/
  datasource:
      driver-class-name: oracle.jdbc.OracleDriver
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        url: 
        username: 
        password: 
        filters: config
        connect-properties:
          #数据库密码加密，加密方法为test下测试类 加密类型为RSA
          config.decrypt: true
          config.decrypt.key: 
  mvc:
    view:
      #模板内容
      prefix: classpath:/templates/
      suffix: .html
    static-path-pattern: /static/**

  thymeleaf:
    cache: false
  jpa:
    open-in-view: false

mybatis:
  mapper-locations: classpath*:/mapper/**.xml
  type-aliases-package: com.ai.ecs.guacamole.mapper
  configuration:
    map-underscore-to-camel-case: true
